### ISSUE TITLE
[Doc Request] Show How to Ignore '.git*' Files

### ISSUE THREAD

**Issue by luxlogica** [git-ftp/git-ftp#339]
Please add an example in the **"Ignoring Files to Be Synced"** section of the manual, showing the *proper* syntax to use in order to ignore the usual ".git*" files - the ones we normally don't want uploaded to testing/staging/production servers (as mentioned in #176) - such as:
- *.gitignore*, 
- *.git-ftp-ignore*, 
- the *.git/* directory itself, 
- *.gitkeep*, 
- and others, like Gitlab's *.gitlab-ci.yml* CI/CD pipeline config files. 

These files seem to follow a simple glob pattern, which rookies (like me), who are not conversant with the command line, will automatically assume to be...:

```
.git*
```

This causes git-ftp to potentially skip files during upload, depending on the file name - I experienced this issue, and it took me a couple of very frustrating days to troubleshoot what I was doing wrong. Adding an example with the proper syntax to the manual, showing newbies that dot-files need to have the dot explicitly escaped, would help greatly:

```
\.git*
```

This may go a little way in also showing how to achieve the functionality wanted in #176.

**Comment by mkllnk** [comment]
Hi, thank you taking the time to bring this up. Is it right that your version of git-ftp is older than 1.1.0?

```sh
    git-ftp --version
```

Git-ftp used regular expressions in old versions. And at some point that was not documented correctly. Newer version use glob patterns as you expected. Here are the patterns for some Git related files:

	.gitignore
	*/.gitignore      # ignore files in sub directories
	*/.gitkeep
	.git-ftp-ignore
	.git-ftp-include
	.gitlab-ci.yml

What do you think about pull request #342?

**Comment by luxlogica** [comment]
@mkllnk Thank you for the pointer. Indeed, I am using Gitlab's "pipelines" feature. Similar to other services, it allows you to implement continuous integration and deployment in your projects, by using Docker containers. In summary, for every repository, you can setup your own Dock container, then run a config script (the 'gitlab-ci.yml' file) which executes shell commands in the container. This allows you, in theory, to configure the container with whatever software you need, and I imagine it would be great for large teams working on complex projects, wanting do to test-driven development, etc. 

In my case, all I want to do is to be able to ftp the files in the web site I'm working on to their shared host server. Git-ftp is a perfect fit. Unfortunately, in order to load git-ftp onto the Docker container, I have to use apt-get:

```
$ apt-get update -qq && apt-get install -y -qq git-ftp
```

It seems that the version apt-get is getting is indeed an old one... I used the `--version` flag in my last build to see the version apt-get was installing:

```
$ git-ftp --version
git-ftp version 0.9.0
```

Now I understand why *so many features* also don't work - e.g., `--auto-init`, etc. :-(

Is 0.9.0 considered to be the last 'stable' version? How come there isn't a newer version to be installed via apt-get?...

**Comment by mkllnk** [comment]
Thank you for sharing this. It looks like they use a Debian stable image which contains that version. https://packages.debian.org/jessie/git-ftp

And it's a Debian policy to include only bugfixes and security patches once a release is stable. I actually have the old-stable Debian Wheezy running on my computer, because I'm too lazy to deal with upgrades and bugs all the time. ;-)

Anyway, you may have two more options here.

1. Can you use wget or curl? Just download the git-ftp version you want from Github. It's only the one shell script. No dependencies. You could do something like this in your pipeline:
```sh
curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > git-ftp
chmod 755 git-ftp
export PATH=".:$PATH"
git-ftp --version
```

2. The other option is to include that one script in your repository. For example, put it into a folder called "scripts" and then add that one to your `PATH` variable or call it straight away with `./scripts/git-ftp`.

**Comment by luxlogica** [comment]
@mkllnk Thank you for your explanation, and for your suggestion: using `curl` worked like a charm! I can now use the latest version of git-ftp within my Gitlab config!

**Comment by jmbelloteau** [comment]
Hi @luxlogica !

I'm on Gitlab too and trying to do exactly what you do with Git-Ftp...
Could you share your **.gitlab.yml** please ? 😄

**Comment by luxlogica** [comment]
@jmbelloteau - here is how we do it. This setup works like this: if you push to your *'develop'* branch, it will automatically upload the changes to your *staging* server; and if you push to your *'master'* branch it will queue up a manual deployment to your live production server (you wouldn't want to automatically deploy to your production server...).

1) In GitLab, go to your project "Settings -> CI/CD Pipelines" page, and define the following 6 variables:
- **STAGE_HOST**: the complete ftp url of the staging server, such as `ftp://ftp.staging.example.com`.
- **STAGE_USERNAME**: the username for the ftp account that will login into the staging server
- **STAGE_PASSWORD**: the password for the ftp login to the staging server
- **PROD_HOST**: ftp url of the production server, such as `ftp://ftp.live.example.com`
- **PROD_USERNAME**
- **PROD_PASSWORD**

2) Add a *'.gitlab-ci.yml'* file to the root folder of your repository, with the following contents:

```
deploy-staging:
  stage: deploy
  script:
    - apt-get update -qq 
    - curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > git-ftp
    - chmod 755 git-ftp
    - export PATH=".:$PATH"
    - git-ftp --version
    - git-ftp push --auto-init -u "$STAGE_USERNAME" -p "$STAGE_PASSWORD" "$STAGE_HOST"
  only:
    - develop
  environment:
    name: staging
    url: http://staging.example.com

deploy-production:
  stage: deploy
  script:
    - apt-get update -qq 
    - curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > git-ftp
    - chmod 755 git-ftp
    - export PATH=".:$PATH"
    - git-ftp --version
    - git-ftp push --auto-init -u "$PROD_USERNAME" -p "$PROD_PASSWORD" "$PROD_HOST"
  only:
    - master
  when: manual
  environment:
    name: production
    url: http://live.example.com
```

3) Now, commit some changes to your local *'develop'* branch, and push them. These changes should automagically appear in your staging server. If you push to your *'master'* branch, the deployment will not be automatic: it will be queued up in the 'Pipelines' page of the project in GitLab. To trigger it, go to that page, and click the 'play' button.

Remember, that depending on your development workflow, you will not want to upload your **entire** project directory to your staging/production servers. In our workflow, for instance, we use 'source' and 'build' folders at the project's root level. We do all our work using HTML/CSS/JS preprocessors (such as Pug, Less, CoffeScript) in the 'source' folder. These then get compiled into finished files in the 'build' folder. So we want to upload *just the 'build' folder*. 

In cases such as this, you need to add the `--syncroot` option to the git-ftp command, to specify which folder you actually want to sync. In our case, we're syncing the *'build'* folder, so it looks like this:

```
- git-ftp push --auto-init --syncroot build -u "$STAGE_USERNAME" -p "$STAGE_PASSWORD" "$STAGE_HOST"
```

I hope this helps!
