### ISSUE TITLE
git-ftp is ignoring artifacts from Bitbucket pipelines build

### ISSUE THREAD

**Issue by Artimal** [git-ftp/git-ftp#408]
Hi,
I am doing Bitbucket pipelines build with following settings:
pipelines:
```
  default:
    - step:
        name: Build and test JS.
        image: node:8.9.3
        script:
          - npm install
          - npm test
          - npm run-script build
    - step:
        name: Build and test PHP.
        image: php:7-fpm
        script:
          - echo "Here will be the Composer build and PHPUnit tests."          
  branches:
    production:
    - step:
        name: Build and test JS.
        image: node:8.9.3
        script:
          - npm install
          - npm test
          - npm run-script build
          - ls
          - ls public_html
        artifacts:
          - public_html/**
    - step:
        name: Build and test PHP.
        image: php:7-fpm
        script:
          - echo "Here will be the Composer build and PHPUnit tests."  
          - ls
          - ls public_html
        artifacts:
          - public_html/**
    - step:
        name: Deploy to FTP.
        image: samueldebruyn/debian-git
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - ls
          - ls public_html
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_HOST
```
ls public_html shows me js, css files and index.html after webpack build, but that files are ignored by git-ftp even when I use .git-ftp-include.

How can I do it? Please for help.
