### ISSUE TITLE
Git-ftp fails

### ISSUE THREAD

**Issue by paulcanning** [git-ftp/git-ftp#429]
Using git-ft in Bitbucket Pipelines, I get the following error:

![failed_git_ftp](https://user-images.githubusercontent.com/1275739/36447479-7685a42e-167c-11e8-9ef2-6ac9f68155bd.PNG)

My yml file looks like this:

```
image: php:7.1.1

pipelines:
  branches:
    develop:
      - step:
          caches:
            - composer
          script:
            - apt-get update
            - apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
      - step:
          name: Deploy
          trigger: manual
          script:
            - apt-get update -qq 
            - curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > git-ftp
            - chmod 755 git-ftp
            - export PATH=".:$PATH"
            - git-ftp --version
            - git-ftp push --auto-init -v --user $FTP_USER --passwd $FTP_PASS ftp://ftp.$FTP_HOST
```

**Comment by mkllnk** [comment]
It looks like git is not installed. The error message is not great, but you can see "git: command not found".

**Comment by paulcanning** [comment]
When I was using apt-get, git-ftp worked. I had to switch to curl installation because I need the latest version due to needing .git-ftp-include to work.

**Comment by mkstix6** [comment]
Thanks @paulcanning. My Pipelines now working with latest git-ftp thanks to your `curl` method.

My bitbucket-pipelines.yml config in case it's useful:

```
options:
  max-time: 5

# Image with git pre-installed
image: samueldebruyn/debian-git

pipelines:
  branches:
    master:
      - step:
          deployment: staging
          caches:
              - node
          name: Build frontend static assets and deploy to staging
          image: node:8.9.3
          script:
              - npm install
              - npm start
              - apt-get update -qq
              # - apt-get -qq install git-ftp
              # apt-get is preferred but only has a very old version of git-ftp
              - curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > git-ftp
              - chmod 755 git-ftp
              - export PATH=".:$PATH"
              - git-ftp --version
              - git status
              - git checkout -- package-lock.json
              - git ftp push --user $FTP_STAG_USER --passwd $FTP_STAG_PW $FTP_STAG_HOST
```
