### ISSUE TITLE
Unable to open public key file

### ISSUE THREAD

**Issue by zilahir** [git-ftp/git-ftp#476]
I am having the following `yml`: 

```
image: php:5.6.31

pipelines: 
  default: 
    - step: 
        script:  
          - apt-get update
          - apt-get -qq install git-ftp
          - chmod 0755 ~/.ssh
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - echo $SSH_KEY_PUBLIC >> ~/.ssh/id_rsa.pub
          - chmod 0644 ~/.ssh/id_rsa.pub
          - echo $SSH_KEY_PRIVATE >> ~/.ssh/id_rsa
          - chmod 0644 ~/.ssh/id_rsa          
          - git ftp catchup --user "$SERVER_USER" --key "~/.ssh/id_rsa" --pubkey "~/.ssh/id_rsa.pub" "sftp://$SERVER_IP/$DEVEL_PATH" -vv --insecure
```

All the variables are containg the proper values. 

But I am not able to get over on this error message whatsoever: 

`SSH public key authentication failed: Unable to open public key file`

Any idea how to solve this?

**Comment by andypillip** [comment]
Hi zilahir.

First let me state that you're apparently using some infrastructure that is beyond git-ftp, and the issue seems to be in the tools that git-ftp is using, not in git-ftp itself.

I would suggest the following, if you didn't do it already:
* Verify if the keys are written correctly into the files
* Try to connect via SSH directly, just to catch errors
* Try without the parameters `--key --pubkey`, since you're using the SSH defaults anyways
* Finally, try to connect via curl, which git-ftp is using, to catch errors on that level

**Comment by DerTanzschuh** [comment]
On some systems the path to a ssh key must be absolute like `/Users/username/.ssh/id_rsa`.

**Comment by davidwebca** [comment]
For those stumbling onto this lately, Bitucket seems to fail to pass the public key which git-ftp requires and it also puts the private key in a specific folder which is /opt/atlassian/pipelines/agent/ssh/id_rsa.

In order to have everything set up properly and be very sure, I used danielstrelec/git-ftp Alpine based image, copy the keys and install ssh-keygen to generate the public key before launching git-ftp.

```yml
pipelines:
  custom:
    init:
      - step:
          name: Init git ftp
          image: danielstrelec/git-ftp
          script:
            - apk update && apk add --no-cache openssh-keygen
            - cp /opt/atlassian/pipelines/agent/ssh/id_rsa ~/.ssh/id_rsa
            - ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
            - cd $BITBUCKET_CLONE_DIR
            - git ftp init -s -v -u "$USERNAME" --key ~/.ssh/id_rsa --pubkey ~/.ssh/id_rsa.pub sftp://$HOST:$PORT_LIVE/$REMOTE_DIR
```
