### ISSUE TITLE
Unrecognised option: sftp://host.com:2222/wp-content/themes/my-theme

### ISSUE THREAD

**Issue by Bobz-zg** [git-ftp/git-ftp#514]
> Tue May  7 09:38:09 UTC 2019: git-ftp version 1.3.1 running on Linux d7f268a7-890f-43f1-904b-377da5f1c2af 4.19.23-coreos-r1 #1 SMP Mon Feb 25 23:40:01 -00 2019 x86_64 x86_64 x86_64 GNU/Linux

I keep on getting: `fatal: Unrecognised option: sftp://host.com:2222/wp-content/themes/my-theme`

Using bitbucket pipeline and I'm not sure what a heck am I doing wrong.
Anyone can enlighten me?

```
image: pyguerder/bitbucket-pipelines-php72

pipelines:
  branches: # Automated triggers on commits to branches
    staging: # -- When committing to staging branch
    - step:
        deployment: production
        script:
          - curl -sL https://deb.nodesource.com/setup_8.x
          - apt-get update
          - apt-get install -y git-ftp
          - git ftp push --auto-init --insecure -vv -u "$FTP_USERNAME" -p "$FTP_PASSWORD" "$FTP_HOST"
```

Try with:
`git ftp push -vv -u "$FTP_USERNAME" -p "$FTP_PASSWORD" --auto-init`
Gives me error: `fatal: Unrecognised option: --auto-init`

If I try without `--auto-init`, only with:
`- git ftp push -vv -u "$FTP_USERNAME" -p "$FTP_PASSWORD" "$FTP_HOST"`

I get error:
`curl: (1) Protocol "sftp" not supported or disabled in libcurl`

A bit inconsistent...

**Comment by Bobz-zg** [comment]
Okay. Turns out that if i use:
```
apt-get update
apt-get install git-ftp
```

I get version 1.3.1 installed... which doesn't have --init-auto :-/

**Comment by Bobz-zg** [comment]
Works now after I created my own docker image with everything I need inside.
So the problem was obviously that:
- docker image I previously used didn't had support for sftp over curl
- apt-get installs old version of git-ftp 1.3.1

Using docker image:
https://cloud.docker.com/repository/docker/codesoup/pumpkin

Deploying my own starter theme:
https://github.com/code-soup/pumpkin

With bitbucket pipeline:
```
image: codesoup/pumpkin

pipelines:
  branches: # Automated triggers on commits to branches
    staging: # -- When committing to staging branch
    - step:
        deployment: production
        script:
          - touch .env
          - echo "ACF_PRO_KEY=$ACF_PRO_KEY" >> .env
          - composer install
          - npm install -g yarn
          - yarn
          - yarn build:production
          - rm -rf .gitignore
          - touch .gitignore
          - echo "node_modules" >> .gitignore
          - echo ".env" >> .gitignore
          - echo ".cache-loader" >> .gitignore
          - git add .
          - git commit -am 'build'
          - git ftp push -vv --auto-init --insecure -f -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_HOST:2222/$FTP_PATH/
```
