### ISSUE TITLE
Unknown SHA1 object

### ISSUE THREAD

**Issue by Bobz-zg** [git-ftp/git-ftp#515]
I'm using bitbucket pipeline to deploy my WordPress theme to WPX hosting.
Things work, but I always get:

```
Wed May  8 04:54:08 UTC 2019: Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
Do you want to ignore and upload all files again? [y/N]: Wed May  8 04:54:08 UTC 2019: Aborting...
```

When running:
```- git ftp push -vv --auto-init --insecure --changed-only -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_HOST:2222/$FTP_PATH/```

I can use `--force` to force deploy everything obviously but I would like to deploy changes only.
I've checked git-ftp.log file that is on my server, and hash in there is ```7f8e7663d185a21a2af0434640e1740e26fe6c6a```

What I get in my pipeline is following:
```
* Connected to uk1.wpxhosting.com (185.5.172.154) port 2222 (#0)
##O#- #                                                                       
* SSH MD5 fingerprint: 745006371aa0ffedffd0e738572da22d
```

I'm not sure how can I debug this, if someone can point me?

**Comment by DerTanzschuh** [comment]
Can you give some more information? 

* What version of git-ftp is running? 
(Another user had the problem that his pipeline had git-ftp 1.3.1 installed over apt-get.)
* Did you set a custom sync-root that is not listed in the command?

git-ftp 1.5.0 introduced some improved handling of syncroot with newer versions of git.

**Comment by Bobz-zg** [comment]
Hi Tanzschuh, thanks for your reply.
If you are referring to this - https://github.com/git-ftp/git-ftp/issues/514 , that was me :)

* git version 2.17.1
* git-ftp 1.5.2

bitbucket-pipelines.yml:
```
image: codesoup/pumpkin

pipelines:
  branches: # Automated triggers on commits to branches
    staging: # -- When committing to staging branch
    - step:
        deployment: production
        script:
          - touch .env
          - echo "ACF_PRO_KEY=$ACF_PRO_KEY" >> .env
          - rm -rf .gitignore
          - touch .gitignore
          - echo ".env" >> .gitignore
          - echo ".cache-loader" >> .gitignore
          - echo "src" >> .gitignore
          - echo "node_modules" >> .gitignore
          - composer install
          - npm install - g yarn
          - yarn
          - yarn build:production
          - git add .
          - git commit -am 'build'
          - git ftp push -vv --auto-init --insecure --changed-only -f -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_HOST:2222/$FTP_PATH/
```

So what I'm doing is:
* `composer install`, to load PHP dependencies 
* `yarn build:production` to compile assets with webpack
* `git commit` to add 'dist' and 'vendor' folder to commit
* `git ftp push` everything over SFTP to my server

I'm not 100% sure is this a way to go, by doing changes in pipeline with composer/build or should I use pipeline only for upload and do `yarn build` / `composer install` locally

Anyhow, when `git ftp push` is triggered following output is visible:

```
git ftp push -vv --auto-init --insecure --changed-only -f -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_HOST:2222/$FTP_PATH/

Wed May  8 05:41:18 UTC 2019: git-ftp version 1.5.2 running on Linux fbb8c5fd-2621-439e-909b-705eab8bd1f3 4.19.23-coreos-r1 #1 SMP Mon Feb 25 23:40:01 -00 2019 x86_64 x86_64 x86_64 GNU/Linux
Wed May  8 05:41:18 UTC 2019: Auto init if needed.
Wed May  8 05:41:18 UTC 2019: Insecure SSL/TLS connection allowed
Wed May  8 05:41:18 UTC 2019: Downloading only changed files.
Wed May  8 05:41:18 UTC 2019: Forced mode enabled.
Wed May  8 05:41:18 UTC 2019: Host is 'uk1.wpxhosting.com:2222'.
Wed May  8 05:41:18 UTC 2019: User is '$FTP_USERNAME'.
Wed May  8 05:41:18 UTC 2019: Password is set.
Wed May  8 05:41:18 UTC 2019: CACert is ''.
Wed May  8 05:41:18 UTC 2019: Insecure is '1'.
Wed May  8 05:41:18 UTC 2019: Proxy is ''.
Wed May  8 05:41:18 UTC 2019: Path is 'wp-content/themes/roderuk/'.
Wed May  8 05:41:18 UTC 2019: Syncroot is './'.
Wed May  8 05:41:18 UTC 2019: The remote sha1 is saved in file '.git-ftp.log'.
Wed May  8 05:41:18 UTC 2019: Check if curl is functional.
Wed May  8 05:41:18 UTC 2019: Retrieving last commit from sftp://$FTP_USERNAME:***@uk1.wpxhosting.com:2222/wp-content/themes/my-theme/.                                                                     
*   Trying 185.5.172.154...
* TCP_NODELAY set
##O#- #                                                                       
* Connected to uk1.wpxhosting.com (185.5.172.154) port 2222 (#0)
##O=#  #                                                                      
* SSH MD5 fingerprint: 745006371aa0ffedffd0e738572da22d
#=#=-#  #                                                                     
* SSH authentication methods available: password
* Initialized password authentication
* Authentication complete
-#O#- #   #                                                                   
-=#=#   #   #                                                                 
-=O#- #  #    #                                                               
{ [41 bytes data]

######################################################################## 100.0%* Connection #0 to host uk1.wpxhosting.com left intact

* Closing connection 0
Wed May  8 05:41:19 UTC 2019: Unknown SHA1 object, could not determine changed files, taking all files.
Wed May  8 05:41:19 UTC 2019: Having files to sync.
Wed May  8 05:41:19 UTC 2019: 699 files to sync:

*** Upload process is going on here ***

* Closing connection 0
Wed May  8 05:44:04 UTC 2019: Last deployment changed from 7f8e7663d185a21a2af0434640e1740e26fe6c6a to 0b8f69e01d109c3a95c690b0d137504fb7a9e80d.
Searching for test report files in directories named [test-results, failsafe-reports, test-reports, surefire-reports] down to a depth of 4
Finished scanning for test reports. Found 0 test report files.
Merged test suites, total number tests is 0, with 0 failures and 0 errors.
```
