### ISSUE TITLE
"Unrecognised option" error when running via Bitbucket pipeline

### ISSUE THREAD

**Issue by metalandcoffee** [git-ftp/git-ftp#542]
Hi there 👋🏾

I attempted to set up a Bitbucket pipeline to deloy via git-ftp using this recommended [video tutorial](https://www.youtube.com/watch?v=8HZhHtZebdw).

However - when the following command is run, I get errors:
`> git ftp push -vv --user $FTP_USERNAME -–passwd $FTP_PASSWORD ftp://12345.server.com`
`> Sat Jul 20 12:47:06 UTC 2019: git-ftp version 1.5.1 running on Linux f853645a-aeb6-49f2-87a5-f6021f59fd7a 4.19.50-coreos-r1 #1 SMP Mon Jun 24 22:08:34 -00 2019 x86_64 GNU/Linux`
`> Sat Jul 20 12:47:06 UTC 2019: fatal: Unrecognised option: $FTP_PASSWORD`

### Environment

git-ftp version 1.5.1 running on Linux (x86_64 GNU/Linux)

**Comment by LukasFritzeDev** [comment]
We are currently fixing a issue connected to this error message (see #522, #533). So maybe the error message is not correct in v1.5.1. :|

Can you echo your environment variables before calling Git-ftp? Do the values show up?

Maybe your `bitbucket-pipelines.yml` could be helpful to fix this here.

**Comment by metalandcoffee** [comment]
Hiya! Thanks a bunch for responding. I am able to successfully `echo` both environment variables. 

Here is what my `bitbucket-pipelines.yml` file looks like:

```
image: samueldebruyn/debian-git

pipelines:
  branches:
    staging:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - echo $FTP_USERNAME
            - echo $FTP_PASSWORD
            - git ftp push -vv --user $FTP_USERNAME -–passwd $FTP_PASSWORD ftp://khisle.pairserver.com

```
