### ISSUE TITLE
Unknown SHA1 object, supposedly not the right branch or something

### ISSUE THREAD

**Issue by WoodrowShigeru** [git-ftp/git-ftp#543]
That same exception has actually cropped up several times in the past, but I still keep getting this error repeatedly.

```
Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
```

https://github.com/git-ftp/git-ftp/issues/244
https://github.com/git-ftp/git-ftp/issues/515

Looking at the .git-ftp.log file on my FTP server and looking for the commit in my local log `$ git log 0ed82d68e8fedca34be2dfb2bbd214fe6248c204` does show that that commit exists, so I don't know what git-ftp is talking about.

The only way I have been able to circumvent this is to delete the log file and push with `git ftp init`. But after a month of work it breaks again.

---

I'm using Bitbucket Pipelines which is set up to deploy from the remote repository to the remote FTP server whenever I push from my local repository to the `release/dev.mysite.com` branch.

[This](https://pastebin.com/xwpTdx1j) is the log for this batch of commands:
```
- apt-get update && apt-get install -qq git-ftp
- echo "$SHELL"
- uname -a
- git-ftp version
- git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_URL -vv
```

---

Pull and push before ftp-push did not work.
```
- apt-get update && apt-get install -qq git-ftp
- git pull
- git push
- git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_URL
```

---

Setting syncroot to `.` did not work.
```
- apt-get update && apt-get install -qq git-ftp
- git config git-ftp.syncroot .
- git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_URL
```

---

Ftp-pushing the very next commit after `0ed82d68e8fedca34be2dfb2bbd214fe6248c204` did not work.
```
- apt-get update && apt-get install -qq git-ftp
- git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_URL --commit ea38616
```

---

Am I using git wrong, perhaps? Is git-ftp maybe not able to handle workloads that are 175 commits old since the last ftp-push? Does merging the master-branch into the feature-branch mess up git-ftp's commit identification?

**Comment by LukasFritzeDev** [comment]
> Am I using git wrong, perhaps?

As far as I can can see the command is correct. But other users had problems with bitbucket pipelines as well. You have linked one of it.

> Is git-ftp maybe not able to handle workloads that are 175 commits old since the last ftp-push?

This shouldn’t be a problem.

> Does merging the master-branch into the feature-branch mess up git-ftp's commit identification?

This shouldn't be a problem as well. As soon as the commit is available in git it should work.

---

Is the entire commit history available in your pipeline or does Bitbucket clone only a part of the history (see [git-clone#depth](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt))?
Just saw in your log you are using `--depth 50` so it might be that the commit from `.git-ftp.log` is not known in the pipeline. Therefore Git-ftp can’t find it.

And another question: Why do you make a reset to a specific commit right after cloning?
```
git reset --hard c9b1b289389b07d79b8522e48e0b5b4d649f8e30
```

**Comment by WoodrowShigeru** [comment]
[depth]: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html#Configurebitbucket-pipelines.yml-ci_depthdepth

Thank you for your time, I appreciate it. I tend to write way-too-long posts.

I've never set the depth. I'm just now learning that it exists. Must be some Bitbucket setting … Yep, [it is][depth]:

> If you don't specify the Git clone depth, it defaults to the last 50, to try and balance the time it takes to clone and how many commits you might need.

That's probably why.

---

> Why do you make a reset to a specific commit right after cloning?

That's interesting. It doesn't come from me either. When comparing recent commits, this command seems to reset to the last commit. Maybe they're trying to be sure?

My whole pipeline config looks like this:

```
# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: samueldebruyn/debian-git

pipelines:
  branches:
    release/dev.mysite.com:
      - step:
          script:
            - apt-get update && apt-get install -qq git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_URL
```

But I'm adding the clown depth now.

Alright, I consider this issue solved. If not, you'll hear from me again next month (^^; )

**Comment by christophengelmayer** [comment]
I just spent several hours debugging a similar issue (using Gitlab-CI).

If you ever run into this problem, **check if you are using the same (latest) git-ftp version on your local machine and in CI**.  

I used the latest version (1.6.0) for the initial ìnit`command from my machine but an outdated (1.3.x) version in my CI script.

**Comment by LukasFritzeDev** [comment]
For everyone who runs into this issue: 

* In gitlab you can set the clone depth at **Settings › CI/CD › General**
* In Bitbucket you can set the `clone-depth` like this:
```yaml
image: ...

clone:
  depth: full            # or higher number than 50

pipelines:
  ...
```
