### ISSUE TITLE
Root folder items are getting pushed through git ftp instead of dist folder through git ftp - bitbucket pipeline

### ISSUE THREAD

**Issue by akmalnawfer** [git-ftp/git-ftp#575]
### Bug / Enhancement / Question ?

```
image: node:10.15.3

pipelines:
  branches:
    master:
     - step:
         name: Build
         script:
           - npm install
           - npm install -g @angular/cli
           - ng build --prod
         artifacts:
           - dist/**
     - step:
         name: Deployment
         deployment: Staging
         script:
           - pipe: atlassian/ftp-deploy:0.3.2
             variables:
               USER: $FTP_USERNAME
               PASSWORD: $FTP_PASSWORD
               SERVER: 18.224.42.18
               REMOTE_PATH: '/'
               LOCAL_PATH: 'dist/*'

```
What am I doing wrong here? I am new to pipelines. I am using a shared server. When I am trying to push the artifacts, only root folder raw files are getting uploaded.
