### ISSUE TITLE
Git LFS support not working for existing repository upgrading to LFS.

### ISSUE THREAD

**Issue by billyromano** [git-ftp/git-ftp#579]
### Bug
My Bitbucket Pipelines have been setup with git-ftp for a long time, but now I have recently introduced git-lfs in the repo.

* How to reproduce the issue?
My pipeline pulled the repo without any LFS command and pushed files with link references instead of binary data. I ran the git lfs pull the next time before the git ftp push and it's showing an error stating: fatal: Dirty repository: Having uncommitted changes. Exiting...
* Can you point to a Git repository to reproduce it?
No.
* Or can you describe the directory structure?
Directory structure is irrelevant.

### Environment

/bin/bash
Linux c8988c39-050f-4978-b62a-c3fcb425b6c0-czv8l 4.19.107-flatcar #1 SMP Thu Mar 26 19:48:36 -00 2020 x86_64 x86_64 x86_64 GNU/Linux
git-ftp version 1.3.3

**Comment by LukasFritzeDev** [comment]
What’s the output of `git status` after running `git lfs pull`? You should be able to test this on your local machine, in case you don’t want to spend ci time for testing.

**Comment by billyromano** [comment]
I figured it out. I needed to install the latest `git` package, as well as, the `git-lfs` package. Once I did that, then I needed to run the `git lfs install` command to make it work. Such a pain, but it works now. I just need to setup a Docker image to cache this setup and make it quicker to run. Here's a sample of my pipelines config:

```YAML
image: madshansen/docker-git-ftp:latest

clone:
  lfs: true
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: production
          script:

            # install dependencies
            - apt-get update
            - apt-get install git
            - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            - apt-get install git-lfs

            # setup git-lfs
            - git lfs install

            # setup git-ftp
            - git config git-ftp.url "$URL_PRODUCTION"
            - git config git-ftp.user "$SFTP_USERNAME"
            - git config git-ftp.password "$SFTP_PASSWORD"
            - git config git-ftp.syncroot .
            - git lfs pull
            - git status
            - git ftp push
```
