### ISSUE TITLE
How to specify the `catchup` option in GitHub actions yml file

### ISSUE THREAD

**Issue by arpit-uno** [git-ftp/git-ftp#616]
Hi,

I have existing files on server and I am deploying to server via [FTP-Deploy-Action](https://github.com/SamKirkland/FTP-Deploy-Action) for github actions. However I am not sure how to specify the catchup option in the .yml file. I guess it should be under `with: ` but what should be the value, a boolean true or the last commit SHA-1. for e.g:

```
with:
        server: myftpserver.xyz.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /domains/xyz.com/public_html/github-actions/
        catchup: true or 4543ssd2d2534332d221321325xzsa
```
Also, should a `.git-ftp-log` with the (last SHA-1) be already present on server, before the action is triggered/runs. Here is complete `main.yml`

```
on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: myftpserver.xyz.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /domains/xyz.com/public_html/github-actions/
```

Any help is appreciated. 

Thanks
