### ISSUE TITLE
Git ftp not upload changes after merge develop to main branch

### ISSUE THREAD

**Issue by YulZhak** [git-ftp/git-ftp#665]
Hello. I'm using bitbucket pipelines with git ftp

### Here is the pipeline
```
    # Pipeline for manual deploy to prod server from the main branch
    deploy-to-production:
      - step:
          name: Manual Deploy to Production Server with git-ftp
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --branch main --all -vv --user $Prod_server_user --passwd $Prod_server_passwd sftp://$Prod_server_addr:22//var/www/html/wordpress/
```
Before using this pipeline I merge develop branch with all changes to main using PR in the bitbucket. After running pipeline this changes are not going to production server. What am I doing wrong& why  is this happening?

If I've merge for example feature branch to develop and then run pipeline for develop branch everything work fine and my changes are goes to test server. What is the difference here?

I tried init, catchup. It didn't help.
